framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        name: PHP_SESSION_LDODB
        cookie_secure: auto
        cookie_samesite: lax
        cookie_path: '%router.request_context.base_url%'
        cookie_domain: '%router.request_context.host%'

    #esi: true
    #fragments: true
    php_errors:
        log: true
